coverage:
  status:
    project:
      default:
        target: 100%
        threshold: 1%
        informational: true
    patch:
      default:
        target: 100%
        informational: true

codecov:
  notify:
    after_n_builds: 2

comment: false
