name: Record Changes Requested

on:
  pull_request_review:
    types: [submitted]

jobs:
  record:
    if: github.event.review.state == 'changes_requested'
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event.pull_request.number }}" > pr_number.txt
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: pr-info
          path: pr_number.txt
